language: java
jdk:
- openjdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
script: "./gradlew clean check assemble"
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: tag IS present
    deploy:
      provider: script
      script: "./gradlew bintrayUpload"
      on:
        tag: true
        all_branches: true
env:
  global:
  - GIT_NAME="Carsten Götzinger"
  - GIT_EMAIL="info@cgo-it.de"
  - secure: vcHgrL9AsHodiDAhw5PyRYwln4UVk96M/k3tHnolol6w1ueEVu2GfVNruz02vs8rbajFVF+vGnZ027SmOanIIQKI3/9C4ZSd/bGVJL1xNudxCvUnXBZ9Fo94vgrlA3ttXlw537Tu3MGcgxuFlXa0jXsgYD8ZNUaVXiKo2bY4r+dgyxTKGl6WzTMyF4EYM/uMKT8V8iOZgO2t3O4/Nt9S4CWWOme0lI65yTMT0G251gVROUJumzv0eMdFFOUn7C+VPeYcYHz9/PAM7nPwqlkaatmvr/PaFLluzM+MiZzTbFWBzIKc4c2o42WE4hlylulJo+RA0o07jSXq6mxeDi7GtiZJiZEi390DRePEu4IG+lrF9cOHSR3LQvZ7QDT8D0/EPyzs+LTaGosyqkbrSwyyrpCGURcp8sXaBRoz2bNyqLKXo36bnS4ACMexlxj5U2lsgZuCJawg0yO9n+qPGE2r37DdnhMIDgci4vy9vqKLBQT1W+Z76vBGFzlTUa8Q+iZJ40dYzZ1AwsyeJSdCOHS/x+OGkjmRkBBq7q/des17Uydjo2dit7T2+eoPyi/PUtKuxa97L+i4NpNDPPQSXlXAAB9oEg8uf4tTmd594bxZkZ0LNLGKi1j32wKK7+MNzmaV9RVpMWkyzRzqNteTEVjxD0TjFsQm5pPL5OM216aVzVk=
  - secure: xN6pbdPEL9tj5bxCNKh9iDepn/+MY04tVrtazs9mrhNCxU97MnsiPQWbCT6NjJx9pWcgpTxNz73/p9DZ+j1K+Uf27adTZCrcgXbAsR3zrHs/tnRKEYyIEApXK2xzpWH5mmNF0esGF8moTJBDXVvToZQ3GEEvcAM+dbQMvbcI/pkfQxDKuOVSWXKtJD6Wei8ZcaiM0GRtSWKmpezZ+7sGReDTTdgxKZdWCTjXjdJ9sIIm9+TWsingBUapS1akKK89QPKKWP6HcTKsVHUrNtrrcELsl6ReIC8YJKkvQx5CXdhnKeqJH6dnjH47jC7wPxjFr5I3stPNIFUJoiFZ3gcw4lCg1SlKCzknZdVF/C59weUAnQ9SVaXAJOuMV4ZMyxsG1KmLIrKEV53nfO78Q7cVoR+ezsZojhz09l/loS6ZvSHMEVmpqnx8FWZy2mKCgT+MdIZ2VSaSlLB9IuywDUxfOZJU1hn99gj3JoNFgPYsSdIvvRvmv5rujwwFffjsNpliNvc4mh+CXoJfPj9jWG9x54OQtbwwJhXqRFe/83rob889wKBxLvQHleSkbnTyq3nXkMQB9qWpNz3cJYSvVfqE4U93q+3Xkbpi4YN3IV9KEDjPzvQqX2847xKydpQE414JSJkwKos/T1ft14jWXVreCBPFkpX5+Wk2eemwDfb7mho=
